package dev.mrkevr.errandapi.errand.api;

public enum ErrandCategory {

	GROCERY_SHOPPING,
	FOOD_DELIVERY,
	PACKAGE_DELIVERY,
	LAUNDRY_SERVICES,
	PET_SERVICES,
	BANKING_TASKS,
	HOME_SERVICES,
	ADMINISTRATIVE_TASKS,
	BOOKING_AND_RESERVATION,
	MISCELLANEOUS;
	
}
